services:
  api:
    build:
      context: ../../
      dockerfile: deployments/api/Dockerfile
    container_name: fridgers-backend-api
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SERVER_URL=${SERVER_URL:-http://0.0.0.0}
      - SERVER_PORT=${SERVER_PORT:-8080}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-fridgers}:${POSTGRES_PASSWORD:-fridgers_password}@host.docker.internal:5432/${POSTGRES_DB:-fridgers}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
